In [1]:
#numpy 

In [3]:
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [7]:
n2=np.array([[1,2,3,4],[2,4,5,6]])

In [8]:
n2

array([[1, 2, 3, 4],
       [2, 4, 5, 6]])

In [9]:
#intializing the numpy 
n3=np.zeros((2,3))

In [10]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#intialzing array with with same number 

In [12]:
np.full((2,2),(10))

array([[10, 10],
       [10, 10]])

In [13]:
#intalizing array within range 

In [15]:
r=np.arange(1,100)

In [16]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
#with skip setps

In [18]:
np.arange(10,105,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [20]:
np.random.randint(100,200,10)

array([104, 118, 194, 102, 104, 110, 100, 174, 180, 170])

In [34]:
#array with shape

In [35]:
n1 = np.array([[1,2,3,4],[2,3,4,5]])

In [36]:
n1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [37]:
n1.shape=(4,2)

In [38]:
n1

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [39]:
n4 = np.array([[1,2,3,4,4],[1,2,4,5,5]])

In [40]:
n4.shape

(2, 5)

In [41]:
#joining numpy arrays 

In [42]:
n1 = np.array([1,2,3,4])

In [43]:
n2 = np.array([1,2,3,4])

In [46]:
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [47]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [49]:
np.column_stack((n1,n2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
#operations of numpy 

In [51]:
n1 = np.array([10,20,30,40,50,60])

In [53]:
n2 = np.array([50,60,70,80,90,100])

In [54]:
np.intersect1d(n1,n2)

array([50, 60])

In [55]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [57]:
#array mathematics addition of array 

In [58]:
n1 = np.array([10,20,30,40])

In [59]:
n2 = np.array([50,60,70,80])

In [60]:
np.sum([n1,n2])

360

In [61]:
np.sum([n1,n2],axis=0)

array([ 60,  80, 100, 120])

In [62]:
np.sum([n1,n2],axis=1)

array([100, 260])

In [ ]:
#basic operations addition ,subtraction ,multoplication,division

In [63]:
n1

array([10, 20, 30, 40])

In [64]:
n1=n1+1

In [65]:
n1


array([11, 21, 31, 41])

In [66]:
n1=n1*10

In [67]:
n1

array([110, 210, 310, 410])

In [68]:
n1=n1-5
n1

array([105, 205, 305, 405])

In [69]:
n1=n1/2
n1

array([ 52.5, 102.5, 152.5, 202.5])

In [ ]:
#mean median standard deviation

In [70]:
np.mean(n1)

127.5

In [73]:
np.median(n1)

127.5

In [74]:
np.std(n1)

55.90169943749474

In [75]:
#save and load 

In [84]:
n1 = np.array([10,20,30,40])

n1=np.save('mynumy',n1)

In [86]:
n2=np.load('mynumy.npy')
n2

array([10, 20, 30, 40])